feat: Endpoint for getting Care Providers data [HANS-292]
nhsx/il-hans-management-interface pull request #10
Opened 2023-03-19 21:17 UTC by grlu75

2023-03-20 18:43 UTC, regularfry requested changes
Looks like a lot of comments but it's actually only a few changes that want working through.  Can't see anything wrong with the functionality, it's all refactoring.

2023-03-20 18:43 UTC, regularfry commented on management_interface/management_interface/views.py
> +    return JsonResponse(json.loads(operation_outcome.json()), status=HTTPStatus.METHOD_NOT_ALLOWED)
The comment is a give-away that this has crossed over the too-hard-to-follow threshold, so we can help out a bit by using the `else` leg of the `if`

```suggestion
    else:
        return failure_response(status=HTTPStatus.METHOD_NOT_ALLOWED,
                                code="not-allowed",
                                diagnostics="Method not allowed - _search only supports POST")
```

2023-03-20 18:43 UTC, regularfry commented on management_interface/management_interface/test_views.py
> +
Think we can pull out something useful here:

```suggestion
    def assertFailure(self, response, status_code, code):
        self.assertEqual(response.status_code, status_code)
        self.assertEqual(response.json()["issue"][0]["code"], code)
```
The `response` object has a `json` method that lets us avoid the `import json` at the top, which is quite handy.

2023-03-20 18:43 UTC, regularfry commented on management_interface/management_interface/test_views.py
> +        self.assertEqual(json.loads(response.content)["issue"][0]["code"], "not-allowed")
```suggestion
        self.assertFailure(response, HTTPStatus.METHOD_NOT_ALLOWED, "not-allowed")
```

2023-03-20 18:43 UTC, regularfry commented on management_interface/management_interface/test_views.py
> +        self.assertEqual(json.loads(response.content)["name"], self.location.name)
```suggestion
        self.assertEqual(response.json()["name"], self.location.name)
```

2023-03-20 18:43 UTC, regularfry commented on management_interface/management_interface/test_views.py
> +        self.assertEqual(json.loads(response.content)["issue"][0]["code"], "not-found")
```suggestion
        self.assertFailure(response, HTTPStatus.NOT_FOUND, "not-found")
```

2023-03-20 18:43 UTC, regularfry commented on management_interface/management_interface/test_views.py
> +        self.assertEqual(json.loads(response.content)["issue"][0]["code"], "required")
```suggestion
        self.assertFailure(response, HTTPStatus.BAD_REQUEST, "required")
```

2023-03-20 18:48 UTC, regularfry commented on management_interface/management_interface/test_views.py
> +
Oh, also for the record I think it's fine for us not to be asserting on the `diagnostics` field here.  I don't think it would gain us very much.

2023-03-22 08:18 UTC, grlu75 commented on management_interface/management_interface/test_views.py
> +    def test_car_care_provider_location_search_bad_request(self):
Good point.

2023-03-23 09:26 UTC, henrywrightPSC commented on management_interface/management_interface/urls.py
> +    path("care-provider-location/_search/", care_provider_search, name="care_provider_search"),
Not yet @regularfry, I think the current thinking is to put it behind an AWS API Gateway and let that do all the auth stuff - likely to be a [private API](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-private-apis.html) as it's internal only plus perhaps some API layer stuff too.

We'll configure the load balancer to only permit `admin/` paths through from the outside world.

2023-03-25 14:43 UTC, merged